### ISSUE TITLE
About last_idx in MASK_IDX bus

### ISSUE THREAD

**Issue by jlong299** [semidynamics/OpenVectorInterface#4]
The last_idx is used to identify the last one of indices for indexed load/store instruction.
Can last_idx be used to identify the last mask_idx.item for strided load/store instruction?  If not, how does CPU know the amount of mask_idx.items it needed? By calculating (vl - vstart)/64?
Thanks.

**Comment by amorenosmd** [comment]
Yes, the last_idx can be used for both masks and indexes. In particular, it indicates the last mask_idx.item to be sent. Even so, in general, the number of elements can be calculated with the vector length. This signal only becomes necessary for the case that the VPU implements the optimization described in 9.2.3: if all the masks are zero after a certain point, the VPU may set last_idx early instead of sending several "masked-out" items.

**Comment by jlong299** [comment]
Thank you so much.
